//PACKAGE KH.FINALPROJ.HOLLOSEKKI.MARKET.CONTROLLER;
//
//IMPORT JAVA.IO.IOEXCEPTION;
//IMPORT JAVA.UTIL.ARRAYLIST;
//IMPORT JAVA.UTIL.HASHMAP;
//
//IMPORT JAVAX.SERVLET.HTTP.HTTPSERVLETREQUEST;
//IMPORT JAVAX.SERVLET.HTTP.HTTPSERVLETRESPONSE;
//IMPORT JAVAX.SERVLET.HTTP.HTTPSESSION;
//
//IMPORT ORG.SPRINGFRAMEWORK.BEANS.FACTORY.ANNOTATION.AUTOWIRED;
//IMPORT ORG.SPRINGFRAMEWORK.STEREOTYPE.CONTROLLER;
//IMPORT ORG.SPRINGFRAMEWORK.UI.MODEL;
//IMPORT ORG.SPRINGFRAMEWORK.WEB.BIND.ANNOTATION.MODELATTRIBUTE;
//IMPORT ORG.SPRINGFRAMEWORK.WEB.BIND.ANNOTATION.REQUESTMAPPING;
//IMPORT ORG.SPRINGFRAMEWORK.WEB.SERVLET.MODELANDVIEW;
//
//IMPORT COM.GOOGLE.GSON.GSON;
//IMPORT COM.GOOGLE.GSON.GSONBUILDER;
//IMPORT COM.GOOGLE.GSON.JSONIOEXCEPTION;
//
//IMPORT KH.FINALPROJ.HOLLOSEKKI.ENROLL.MODEL.VO.USERS;
//IMPORT KH.FINALPROJ.HOLLOSEKKI.MARKET.MODEL.SERVICE.MARKETSERVICE;
//IMPORT KH.FINALPROJ.HOLLOSEKKI.MARKET.MODEL.VO.ATTENDANCE;
//
//@CONTROLLER
//PUBLIC CLASS ATTENDANCECONTROLLER {
//	
//	@AUTOWIRED
//	PRIVATE MARKETSERVICE MKSERVICE;
//	
//	
//	@REQUESTMAPPING("ATTENDANCE_CHECKING.MA")
//	PUBLIC VOID ATTENDANCECHECK(HTTPSESSION SESSION, HTTPSERVLETRESPONSE RESPONSE, @MODELATTRIBUTE ATTENDANCE AT, MODEL MODEL) {
//		USERS U = (USERS) SESSION.GETATTRIBUTE("LOGINUSER");
//		HASHMAP<STRING, OBJECT> MAP = NEW HASHMAP<STRING, OBJECT>();
//		MAP.PUT("AT", AT);
//		MAP.PUT("U", U);
//	
//		INT RESULT = MKSERVICE.ATTODAYCHECKED(U);
//		IF(RESULT < 1) {
//			MKSERVICE.ATINSERT(MAP);
//			MKSERVICE.GETTEDPOINT(MAP);
//			MKSERVICE.GETMONTHPOINT(MAP);
//			MKSERVICE.ADATECHECK(MAP);
//		}
//				
//		ARRAYLIST<ATTENDANCE> ATLIST = MKSERVICE.ALLAT(U);
//		GSONBUILDER GB = NEW GSONBUILDER().SETDATEFORMAT("YYYY-MM-DD");
//		GSON GSON = GB.CREATE();
//		STRING JSON = GSON.TOJSON(ATLIST);
//		TRY {
//			RESPONSE.GETWRITER().WRITE(JSON);
//		} CATCH (IOEXCEPTION E) {
//			E.PRINTSTACKTRACE();
//		}
//		MODEL.ADDATTRIBUTE("RESULT", RESULT);
//		
//    }
//	    		
//
//	@REQUESTMAPPING("ATTENDANCE_CHECK.MA")
//	PUBLIC MODELANDVIEW ATTENDANCECHECKING(HTTPSESSION SESSION,MODELANDVIEW MV,HTTPSERVLETREQUEST REQUEST){
//	    USERS U = (USERS) SESSION.GETATTRIBUTE("LOGINUSER");
//	    INT RESULT = MKSERVICE.ATTODAYCHECKED(U);
//	    REQUEST.SETATTRIBUTE("RESULT", RESULT);
//	    
//		STRING VIEWPAGE = "ATTENDANCE_CHECK";
//		ARRAYLIST<ATTENDANCE> CALENDAR = NULL;
//		TRY {
//			CALENDAR = MKSERVICE.ALLAT(U);
//			REQUEST.SETATTRIBUTE("CALENDARLIST", CALENDAR);
//		} CATCH (EXCEPTION E) {
//			E.PRINTSTACKTRACE();
//		}
//		MV.SETVIEWNAME(VIEWPAGE);
//		RETURN MV;
//	}	    
//	    	
//	@REQUESTMAPPING("POINT.MA")
//	PUBLIC VOID SENDPOINT(HTTPSESSION SESSION, HTTPSERVLETRESPONSE RESPONSE) {
//		USERS U = (USERS) SESSION.GETATTRIBUTE("LOGINUSER");
//		USERS LIST = NULL;
//		IF(U != NULL) {
//			LIST = MKSERVICE.SENDPOINT(U);
//		}
//		RESPONSE.SETCONTENTTYPE("APPLICATION/JSON; CHARSET=UTF-8"); 
//		GSONBUILDER GB = NEW GSONBUILDER().SETDATEFORMAT("YYYY-MM-DD");
//		GSON GSON = GB.CREATE();
//		TRY {
//			GSON.TOJSON(LIST, RESPONSE.GETWRITER());
//		} CATCH (JSONIOEXCEPTION | IOEXCEPTION E) {
//			E.PRINTSTACKTRACE();
//		}
//		
//
//	}
//}
